### ISSUE TITLE
Не могу понять. Как сделать кнопки внутри сообщения?

### ISSUE THREAD

**Issue by ParanoikTemp** [node-vk-bot-api/node-vk-bot-api#105]
Как сделать мини - кнопки которые внутри сообщения. Очень надо

**Comment by GreinOne** [comment]
В мотоде sendMessage или reply нужно отправить такой Markup:

```javascript
const Markup = require('node-vk-bot-api/lib/markup');
Markup.keyboard([
    Markup.button('INLINE_BUTTON', 'primary')
        ]).inline(true);
```

**Comment by Zimtir** [comment]
Как отловить какая кнопка была нажата?

**Comment by GreinOne** [comment]
> Как отловить какая кнопка была нажата?

Через payload, в ctx.message.payload

**Comment by Zimtir** [comment]
@GreinOne то есть при этом функция отлова как будет выглядеть?

```
    command(**ТУТ ЧТО УКАЗАТЬ?**, (ctx: any) => {
      console.log(ctx.message.payload)
    })
```

**Comment by GreinOne** [comment]
@Zimtir label кнопки

**Comment by Zimtir** [comment]
@GreinOne то есть мы привяжемся к label кнопки, а как мне получить payload?
VK при нажатии на кнопку просто эмулирует вписывание текста из Label но payload он не пропускает

**Comment by GreinOne** [comment]
@Zimtir да логика такая, а уже по payload можно сделать проверку, действительно ли это та кнопка и/или передать какие-то параметры, если нет payload, значит что-то не так отправляется, payload должен быть в формате JSON 

```JavaScript
Markup.button('Button label', 'primary', { "param": "value" })
```

[Такой должен быть ответ](https://i.imgur.com/lwKS9UT.png)
