### ISSUE TITLE
LongPolling always returns 'Rate limit reached' error

### ISSUE THREAD

**Issue by PetyaT** [node-vk-bot-api/node-vk-bot-api#119]
LongPolling always returns `error_code: 29, error_message: 'Rate limit reached'`. 

Callback API works fine though, but it would be nice to quickly test some ideas with longpolling without setting up a server.

**Comment by PetyaT** [comment]
It was a VK server-side problem, LongPolling works fine now.

**Comment by Latnok** [comment]
аналогичная проблема
бесконечно получаю 'Rate limit reached'
