### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by bigHapiness** [node-vk-bot-api/node-vk-bot-api#16]
При попытке отписать какое-либо сообщение в группу на стороне сервера возникает ошибка

(node:2676) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'toLowerCase' of undefined
    at VkBot.module.exports (C:\Users\79520\Desktop\wf\lib\methods\startPolling.js:39:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by bifot** [comment]
Какой тип события?

**Comment by bigHapiness** [comment]
Да, идёт обработка message_new
Вызов toLowerCase идёт в
./lib/utils/next:4
`const message = ctx.message.body.toLowerCase() ` фиксит.
```
bot.event('message_new',(msgobj)=>{
    console.log(msgobj);
})
``` 
Подобное вовсе не работает, не вызывает колбэк.
А вот по `bot.on('message_new',cb)` срабатывает, но дропает ошибку.
```
(node:30566) UnhandledPromiseRejectionWarning: TypeError: fn is not a function
    at fn (/var/www/wfbot/node_modules/node-vk-bot-api/lib/methods/command.js:8:18)
```
p.s: cb - действительно функция

Спасибо за внимание к ошибке.

**Comment by bifot** [comment]
Изначально `event` метод не предназначался для таких кейсов, но я выпустил багфикс, теперь можно использовать `bot.event('message_new', (ctx) => {})`, но это бессмысленно, потому что для такого обработчика есть сахар в виде `bot.on((ctx) => {})`. https://github.com/node-vk-bot-api/node-vk-bot-api/commit/dd8f1c640764ebd41f1e55e1455bf5508f13cfec
