### ISSUE TITLE
Бот отвечает несколько раз.

### ISSUE THREAD

**Issue by arpavlyutkin** [node-vk-bot-api/node-vk-bot-api#20]
`bot.command('Начать', (ctx) => {
   ctx.reply('Hello!')
})`

Ввожу "Начать"
Бот отправляет 2 сообщения "Hello", бывает и больше.
В чем проблема может быть?

**Comment by bifot** [comment]
Возможно, запущено два поллинга. Проверь это.

**Comment by AlexTolmachev** [comment]
Целиком бы код глянуть

**Comment by arpavlyutkin** [comment]
![screen](https://user-images.githubusercontent.com/43100259/45263754-675b3900-b438-11e8-8dea-3f866964cb72.png)
`const VkBot = require('node-vk-bot-api')

const bot = new VkBot({
  token: "",
  group_id: ""
})

bot.command('/start', (ctx) => {
  ctx.reply('Hello!')
})

bot.startPolling()`

**Comment by arpavlyutkin** [comment]
Код из примера

**Comment by arpavlyutkin** [comment]
`{"error":{"error_code":6,"error_msg":"Too many requests per second","request_params":[{"key":"oauth","value":"1"},{"key":"method","value":"execute"},{"key":"v","value":"5.8"},{"key":"code","value":"return [ API.messages.send({\"v\":\"5.80\",\"user_ids\":\"381879723\",\"message\":\"Hello!\",\"attachment\":\"\",\"keyboard\":null}),API.messages.send({\"v\":\"5.80\",\"user_ids\":\"381879723\",\"message\":\"Hello!\",\"attachment\":\"\",\"keyboard\":null}),API.messages.send({\"v\":\"5.80\",\"user_ids\":\"381879723\",\"message\":\"Hello!\",\"attachment\":\"\",\"keyboard\":null}),API.messages.send({\"v\":\"5.80\",\"user_ids\":\"381879723\",\"message\":\"Hello!\",\"attachment\":\"\",\"keyboard\":null}) ];"}]}}`

**Comment by bifot** [comment]
Во-первых, непонятно, каким образом ловится ошибка "Too many requests per second", если у тебя запущен бот и пишешь ему только ты.

Во-вторых, я протестил этот код на последней версии пакета, все работает отлично:

![image](https://user-images.githubusercontent.com/5220114/45264077-37fbfa80-b43f-11e8-9002-6da5540f01d1.png)

**Comment by arpavlyutkin** [comment]
В чем проблема тогда может быть? Похоже, только у меня такая проблема

**Comment by arpavlyutkin** [comment]
Такая проблема только на локалке, странно.
На сервере все без проблем работает

**Comment by bifot** [comment]
Какой пункт был выбран, помимо "Входящее сообщение"?

**Comment by arpavlyutkin** [comment]
Все из категории "Сообщения"
