### ISSUE TITLE
Правильная версия API

### ISSUE THREAD

**Issue by InkOut** [node-vk-bot-api/node-vk-bot-api#21]
По какой-то причине VK использует версию API из настроек паблика, а не из кода.

Пришлось долго разбираться, пока не выяснил, что надо и в самом паблике установить версию 8.40.

Мб написать это в инструкции?

**Comment by bifot** [comment]
Версия 8.40? Такая разве есть?

По поводу того, что версия должна быть в самом паблике тоже указана, как и у бота, очевидно, но можешь закинуть пулл реквест, добавив строку в ридми про это.

**Comment by InkOut** [comment]
Сорри, ошибся. Версия - 5.40. Из описания не очевидно, что бот использует 5.40. Вечером сделаю реквест
