### ISSUE TITLE
Проблема при обработке событий без поля text

### ISSUE THREAD

**Issue by Chappa74** [node-vk-bot-api/node-vk-bot-api#25]
Привет, пытался повесить на бота обработку события при подписке на группу (group_join), но бот никак не реагировал

```
 bot.event('group_join', (ctx) => {
       console.log('Im get group_join event')
 });
```
Порылся в исходниках, заметил, что при получении данного события вылетает на этом моменте:
./lib/methods/next.js:4

`const message = ctx.message.text.toLowerCase()`

посмотрел тело сообщения, которое приходит от vk, в нем отсутствует поле text как таковое, 

`{ user_id: id, join_type: 'join', type: 'group_join' }`

пришлось добавить проверку на наличие text, так же, в данном случае не сработает `ctx.reply('text')`, поскольку поле peer_id заменено полем user_id, впрочем, здесь обошелся методом `bot.send`

Проверьте, пожалуйста.

**Comment by bifot** [comment]
Привет! Спасибо за то, что написал о баге.

> пришлось добавить проверку на наличие text

Создай пулл реквест и отправь его, если не заставит трудом, так баг будет пофикшен быстрее.

> в данном случае не сработает ctx.reply('text'), поскольку поле peer_id заменено полем user_id

Какая это версия API?

**Comment by Chappa74** [comment]
Версия api 5.80. Судя по [документации вк](https://vk.com/dev/groups_events), peer_id используется только для личных сообщений, для большинства остальных событий сообществ используется user_id

ну и сама ошибка при получении событий без peer_id и вызове ctx.reply('text'):

`Execute Error: {"method":"execute","error_code":100,"error_msg":"One of the parameters specified was missing or invalid: you should specify peer_id, user_id, domain, chat_id or user_ids param"}`

Пулл реквест добавлю в течение дня

**Comment by bifot** [comment]
Спасибо за пулл реквест. Пакет обновлен и этот багфикс доступен с версии `2.1.2`.
