### ISSUE TITLE
Как использовать payload?

### ISSUE THREAD

**Issue by HulioEglesias** [node-vk-bot-api/node-vk-bot-api#34]
Я в кнопку еще пишу пейлоад ` Markup.button('Button1', 'default', "asd")`
Как мне получить его при нажатии на кнопку?

**Comment by bifot** [comment]
https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/lib/context.js
https://vk.com/dev/bots_docs_3?f=4.%2B%D0%9A%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B%2B%D0%B4%D0%BB%D1%8F%2B%D0%B1%D0%BE%D1%82%D0%BE%D0%B2
