### ISSUE TITLE
Единый контекст сцен на всех пользователей

### ISSUE THREAD

**Issue by MiklerGM** [node-vk-bot-api/node-vk-bot-api#37]
При обращении к боту от разных пользователей контекст и состояние сцены не уникальное для каждого пользователя. 
Полностью воспроизводится на [примере](https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/examples/scene.js) работы со сценами

Для воспроизвдения необходимо 2 пользователя U1, U2 и бот:
```
U1-B -> /meet
B-U1 -> How old are you?
U2-B -> hello
B-U2 -> What Is your name?
```
Подобное поведение описано #35 

Воспроизвел на версии 2.4.2 и 2.4.0

**Comment by pikss86** [comment]
У меня такое было, когда я забыл поменять версию API в настройках группы, id сессии был undefined из-за того что в ответе на запрос к API небыли нужного поля

**Comment by MiklerGM** [comment]
Хм, в эту сторону я не смотрел. Я использую **callback api** и версию 5.50
