### ISSUE TITLE
Exceptions are suppressed in command handlers

### ISSUE THREAD

**Issue by handlerug** [node-vk-bot-api/node-vk-bot-api#41]
When I am throwing exception (even manually) from command handler (picture below), it gets suppressed and not handled by Sentry, other ravenjs-library and even by `try-catch` code expression:

![image 2019-02-03 18 08 38](https://user-images.githubusercontent.com/24986597/52175968-bc7c5a80-27de-11e9-8d14-a9a326edea23.jpg)

It should be handled and logged or passed to global scope handler (if exists).

**Comment by bifot** [comment]
Fixed in `node-vk-bot-api@2.4.6`.
