### ISSUE TITLE
Can't find a way to access reply_message // Как использовать ответ на сообщение?

### ISSUE THREAD

**Issue by Slate245** [node-vk-bot-api/node-vk-bot-api#53]
There is a property of message object called "reply_message", listed in VK API. You can assign a message object to it to specify to which message bot is replying, However, I can't find a way to use this functionality in the bot API, because it seems that everything you provide in sendMessage method is interpreted as an attachment,
---
Во вконтактовском API указано свойство объекта сообщения "reply_message", которому можно присвоить объект сообщения, на которое бот отвечает. Не могу найти возможность использовать этот функционал в API бота, поскольку все, что передаешь в метод sendMessage воспринимается как attachment.

**Comment by bifot** [comment]
See advanced usage.

https://github.com/node-vk-bot-api/node-vk-bot-api#sendmessageuserid-message-attachment-keyboard-sticker
