### ISSUE TITLE
How to use payload in buttons?

### ISSUE THREAD

**Issue by HulioEglesias** [node-vk-bot-api/node-vk-bot-api#54]
Can't to get a payload from button.
`bot.command('start', (ctx) => {
  ctx.reply('Hello', null, Markup
  .keyboard([
    [Markup.button('First', 'positive', {qwe: 'asd'})]
  ]))
})`

1. Send message 'start'
2. Press button "First"
And I can't find my payload data.

**Comment by bifot** [comment]
You can use [`.on`](https://github.com/node-vk-bot-api/node-vk-bot-api#onmiddlewares) handler for this.

```js
bot.command('/start', (ctx) => {
  ctx.reply('Hello?', null, Markup
    .keyboard([
      [
        Markup.button('Hi', 'primary', {
          foo: 'bar',
        }),
      ],
    ]));
});

bot.on((ctx) => {
  console.log(ctx.message.payload); // '{"foo":"bar"}'
});
```

Also you can use for your case unstable version with [`.button`](https://github.com/node-vk-bot-api/node-vk-bot-api/tree/button-trigger#buttontriggers-middlewares) method.

**Comment by HulioEglesias** [comment]
`.on` isn't work.

**Comment by bifot** [comment]
Before I wrote my comment, I checked the code. All fine.

**Comment by HulioEglesias** [comment]
Can't do it =(
![Screenshot_1](https://user-images.githubusercontent.com/15662060/56458383-4def7780-639f-11e9-85e5-35ba21a66abf.png)
![Screenshot_2](https://user-images.githubusercontent.com/15662060/56458384-50ea6800-639f-11e9-89c7-513c73bdbdce.png)

**Comment by bifot** [comment]
Try to use latest version of node-vk-bot-api and VK API.  If you any questions, you can ask community in [telegram community chat](https://t.me/joinchat/BXuo0kxMRNVyfdKKjMHpQQ).

![image](https://user-images.githubusercontent.com/5220114/56459022-d1f13180-6396-11e9-9763-34de1a8da05e.png)
