### ISSUE TITLE
bot not response longpool

### ISSUE THREAD

**Issue by drunkod** [node-vk-bot-api/node-vk-bot-api#55]
Бот не отвечает при использовании longpoolapi:
При отправке боту вложения с записью типа wall, с вложениями более 6 фотографий...
Если отправить в сообщения сообществ эту, то не работает:https://vk.com/wall407487806_537
Событие не отслеживается даже тут: bot.on(ctx => {
  
});

Если отправить эту, то работает:https://vk.com/wall407487806_520
И событие отслеживается.

В вебхуках данный пример работает вне зависимости от количества вложений в отправленной записи типа wall.

**Comment by del333ted** [comment]
@bifot close issue
