### ISSUE TITLE
Как создать сессию чата?

### ISSUE THREAD

**Issue by starcevpro** [node-vk-bot-api/node-vk-bot-api#56]
Как создать сессию чата? Или можно только пользователя чата? Добавьте такую функцию...

**Comment by bifot** [comment]
Ничего не понятно из твоего сообщения.

**Comment by starcevpro** [comment]
По дефолту модуль Session хранит сессию для определенного пользователя в определенной беседе, но что если нужно записать в оперативку переменную самого чата и если кто-то из этого чата отправит сообщение то Session вернет переменную в ctx. Если и это не понятно, то я не знаю как обьяснить =с

> Как создать сессию чата? Или можно только пользователя чата? Добавьте такую функцию...

**Comment by bifot** [comment]
Пиши в коммьюнити ват.
