### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by sc4m-ua** [node-vk-bot-api/node-vk-bot-api#59]
Code:
```
const VkBot = require('node-vk-bot-api')

const bot = new VkBot("MYTOKENHERE");

bot.command('/start', (ctx) => {
  ctx.reply('Hello!')
})

bot.startPolling(() => {
  console.log('Bot started.')
})
```
Error:
> (node:12168) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at VkBot.module.exports (C:\Users\Yaroslav\Desktop\bots\vk bot\node_modules\node-vk-bot-api\lib\api.js:17:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by WILDDIP** [comment]
Интернет включи :)
