### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by bukhalo** [node-vk-bot-api/node-vk-bot-api#64]
"node" need to be removed from the package name. Ref: https://docs.npmjs.com/files/package.json#name

> Don’t put “js” or “node” in the name. It’s assumed that it’s js, since you’re writing a package.json file, and you can specify the engine using the “engines” field. (See below.)

**Comment by bifot** [comment]
"vk-bot-api" is already reserved. Ref: https://www.npmjs.com/package/vk-bot-api
