### ISSUE TITLE
Проблема!

### ISSUE THREAD

**Issue by drocsfox11** [node-vk-bot-api/node-vk-bot-api#67]
const scene = new Scene('meet',
  (ctx) => {
    ctx.scene.next()
    ctx.reply('How old are you?')
  },
  (ctx) => {
    ctx.session.age = +ctx.message.text

    ctx.scene.next()
    ctx.reply('What is your name?')
  },
  (ctx) => {
    ctx.session.name = ctx.message.text

    ctx.scene.leave()
    ctx.reply(`Nice to meet you, ${ctx.session.name} (${ctx.session.age} years old)`)
  },
)
const session = new Session()
const stage = new Stage(scene)

bot.use(session.middleware())
bot.use(stage.middleware())

bot.command('/meet', (ctx) => {
  ctx.scene.enter('meet')
})

Скрипт не является рабочим! При записи в  ctx.session.age и выводе  (${ctx.session.age} ответ Nan или undefined! В чем причина. Переписывал,как только мог. Не работает.

**Comment by bifot** [comment]
Use the latest version of VK API.
