### ISSUE TITLE
ctx.reply не отправит клавиатуру если передать сообщение как объект

### ISSUE THREAD

**Issue by nnqq** [node-vk-bot-api/node-vk-bot-api#74]
При вызове `ctx.reply` с объектом первым аргументом, клавиатура просто не попадает в конечный `execute`, а вырезается в либе где то по дороге

```
ctx.reply({
  message: 'Test',
  dont_parse_links: 1,
}, null, Markup.keyboard(['Never appear']));
```

Сообщение будет валидно отправлено, но без клавиатуры потому что ее нету в `execute`

**Comment by bifot** [comment]
https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/lib/methods/sendMessage.js#L16

```js
ctx.reply({
  message: ‘Hello, world!’,
  keyboard: Markup.keyboard([‘foo’, ‘bar’]).toJSON(),
});
```
