### ISSUE TITLE
Дополнительные поля для messages.send

### ISSUE THREAD

**Issue by starcevpro** [node-vk-bot-api/node-vk-bot-api#77]
Я бы хотел добавить параметры:
disable_mentions
dont_parse_links
Добавьте возможность в reply. Или просто дайте пользователям указывать JSON объект со всеми возможными параметрами для messages.send

Или если это возможно, то объясните как.)

**Comment by bifot** [comment]
Привет! Ты можешь вызвать метод `bot.sendMessage` или `ctx.reply` со своими параметрами.

Выглядеть это будет так:

```
ctx.reply(1, {
  message: 'Hello, world!',
  sticker_id: 1,
  ...,
});
```

**Comment by starcevpro** [comment]
Спасибо!
