### ISSUE TITLE
Using with serverless

### ISSUE THREAD

**Issue by happylolonly** [node-vk-bot-api/node-vk-bot-api#78]
Hi, how can I use bot API with serverless?
Can I somehow wrap your package?

Thanks.

**Comment by bifot** [comment]
Hello! You can create server (koa/express) and connect [Callback API](https://github.com/node-vk-bot-api/node-vk-bot-api#webhookcallbackargs).

**Comment by happylolonly** [comment]
Hi @bifot , can use it with serverless (lambda functions)?

or what I can do to use with them?

**Comment by bifot** [comment]
I don’t have any experience with serverless but I think you need to create your function (as endpoint for internet), setup webhooks from VK and receive needed events (new message from client for example).

**Comment by bifot** [comment]
You can check examples in the repository (see examples folder), I wrote two applications with webhook support on koa & express.

**Comment by happylolonly** [comment]
hi, I don't think this issue can be closed
this library don't support serverless, it will be good to add it

**Comment by bifot** [comment]
Why you can't use webhooks api?
