### ISSUE TITLE
Object Markup.

### ISSUE THREAD

**Issue by zababurinsv** [node-vk-bot-api/node-vk-bot-api#82]
I included this module in my js application.

Please tell me what kind of object in your example is Markup?

Markup.keyboard(buttons, options): Create keyboard
Markup.button(label, color, payload): Create custom button
Markup.oneTime(): Set oneTime to keyboard

Where can i getting this object ?

**Comment by bifot** [comment]
Hi,

You need to simply import module via require:

```
const Markup = require('node-vk-bot-api/lib/markup');

Also you can check [this example](https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/examples/keyboard.js).
```
