### ISSUE TITLE
Doesn't work keyboard from example

### ISSUE THREAD

**Issue by HulioEglesias** [node-vk-bot-api/node-vk-bot-api#88]
This example doesn't work https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/examples/keyboard.js

I got an error:
`(node:3152) UnhandledPromiseRejectionWarning: #<Object>
(node:3152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

**Comment by beautyfree** [comment]
same

**Comment by beautyfree** [comment]
okay, it's required this:
"To enable the keyboard in the community, go to Manage -> Messages -> Bots and turn on “Bot abilities. You can also add the Start button there."

https://vk.com/dev/bots_docs_3?f=4.1.%20Setup
