### ISSUE TITLE
(node:29740) UnhandledPromiseRejectionWarning: undefined

### ISSUE THREAD

**Issue by NoTwerkkk** [node-vk-bot-api/node-vk-bot-api#92]
При каждом запуске бота и при попытке отправить сообщение, ловлю эту ошибку.
Пробовал скрыть это этой функцией - process.on('unhandledRejection', error => { 
});
Но при любом catch'e у самого метода вк ловится эта херня.
![image](https://user-images.githubusercontent.com/45132321/77905220-c46a4a00-727d-11ea-8e46-c5b5505b0ad1.png)
До этого пользовался старой версией модуля 2.4.9 с ней все было нормально, но на ней не было inline кнопок.

**Comment by bifot** [comment]
Попробуй отлавливать ошибку в момент отправки самого сообщения, то есть:

```js
try {
  await ctx.reply('hello, world!');
} catch (e) {
  console.error(e);
}
```

**Comment by NoTwerkkk** [comment]
Пробовал, не помогло, все то же и самое

**Comment by bifot** [comment]
Обновись до `3.3.4`, там эта проблема решена.
