### ISSUE TITLE
ApiError, хотя всё выполнилось без ошибки

### ISSUE THREAD

**Issue by kirillzver** [node-vk-bot-api/node-vk-bot-api#96]
Два дня назад я столкнулся с проблемой описанной здесь: https://github.com/node-vk-bot-api/node-vk-bot-api/issues/92
Сегодня увидел, что пришло обновление 3.3.4, где она исправлена. На деле же, теперь вместо undefined выводит:
![image](https://user-images.githubusercontent.com/61228783/79065488-42d0de00-7cb9-11ea-9180-e9d71b075364.png)
А сообщение отправляется. По факту: ошибка лишняя.

**Comment by NoTwerkkk** [comment]
Такая же беда, апдейт ничего не пофиксил, теперь прост другая ошибка .-.

**Comment by bifot** [comment]
https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/README.md#error-handling
